name: Build Custom Marauder

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: pio run -e esp32dev

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-marauder-custom-bin
          path: .pio/build/**/*.bin
          
