name: Build Custom Marauder

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Board Core
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.11

      - name: Install Required Libraries
        run: |
          arduino-cli lib install "LinkedList"
          arduino-cli lib install "TFT_eSPI"
          arduino-cli lib install "JPEGDecoder"
          arduino-cli lib install "ArduinoJson"
          mkdir -p ~/Arduino/libraries
          git clone https://github.com/marian-craciunescu/ESP32Ping.git ~/Arduino/libraries/ESP32Ping
          git clone https://github.com/h2zero/NimBLE-Arduino.git ~/Arduino/libraries/NimBLE-Arduino

      - name: Compile Marauder Firmware
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./build esp32_marauder

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-marauder-custom-bin
          path: ./build/*.bin
          
